name: CI
on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # TODO: windows
        emacs_version:
          # - 25.3
          # - 26.3
          # - 27.2
          - 28.1
          # - snapshot
        miniconda_version:
          # - 4.6
          - 4.7
          - 4.8
          # - 4.9
          # - 4.10
          # - 4.11
          - 4.12
          # - 4.13
    steps:
      - uses: purcell/setup-emacs@v3.0
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: ${{ matrix.miniconda_version }}
      - name: create conda environment foo
        run: conda create -y -n foo python=3.10
      - uses: actions/checkout@v2
      - name: install dependencies & run tests
        run: >-
          emacs -Q --batch -L .
          --load "ci/deps.el"
          --load "conda.el"
          --load "test/conda-test.el"
          -f ert-run-tests-batch-and-exit
